travis:
  secure:
    BINSTAR_TOKEN: EnntCJPkTf6J9Hljl1bc0WHR/C2mLjiUurM9QGunYJObiK9DmI/WEi2htSxbU3FhcpYx8XWx6tTw876KM4jotl3PLEN8SVYZX7PYFRzFpoitPRT08+35ZcsLns0Yt7rlxgHx662+uZXxaWmY32V3ssyH4HdZn5bgNW5y2cGU5zdw5JNZbjNcCk4M7VSk6JZ9WclkZnnRgY0teLIIRFR5Q47fzmPrvPEHLVPW0+2YwQmu9kDm7hcArGI9qCiDME2Hazu7CMWMFvEx6T5bkU8RzHTwbrqYmOafl+7dq0A1hhdAScE3tTa8x20kFHVUkDhozJzIylchiGJbWhcgEENO2jUDRm3tlomkY6nVW8dVrQ58NRbHA6X7USNtUNi04+M+7/pk3nanHA1q9h4dH8wNZPXCVnlzw2sttlQiqd/ylpZp86ES7xup7A0uZy6bb1voEWeCaIWeXvN2b9HRQ8J3Y8EPFIvlXqv8hmVKP2wvGo1XgEN5qbSqqPAOdPkghffEtBZW34f8W98VXDegK+PMQ1wrB+iS+mOoPqWDLHOKQ+d+jYHs0CTBJcxKot38yOcXSXYGPxq+f8hoHAfANC3Fb3z19gdIlS+UiuF9wcOu5wPgUFCragkB0qNMbjKEk2MwMO82vUooydnVfKzUHqKQOQq6cKkwCbjD8dqh2Ua82qU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
